version: '3.5'

services:
  postgres:
    image: 'postgres:13.5-alpine'
    restart: always
    ports:
      - '${TYPEORM_PORT}:5432'
    volumes:
      - ./db/postgresql/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${TYPEORM_USERNAME}
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
      - POSTGRES_DB=${TYPEORM_DATABASE}
    networks:
      - postgres

networks:
  postgres:

volumes:
  postgres:
